// Feature name to human-readable label mapping
// Used in Explainability component to display driver names
export const FEATURE_LABELS = {
  "bci_index": "Baltic Capesize Index (BCI)",
  "bdi_index": "Baltic Dry Index (BDI)",
  "bci_ma_7": "BCI 7-Day Moving Average",
  "bci_ma_14": "BCI 14-Day Moving Average",
  "bci_ma_30": "BCI 30-Day Moving Average",
  "bci_ma_60": "BCI 60-Day Moving Average",
  "bci_std_7": "BCI 7-Day Volatility",
  "bci_lag_1": "BCI Yesterday",
  "bci_lag_7": "BCI 7 Days Ago",
  "bci_lag_14": "BCI 14 Days Ago",
  "bci_lag_30": "BCI 30 Days Ago",
  "bdi_lag_1": "BDI Yesterday",
  "bdi_lag_7": "BDI 7 Days Ago",
  "bdi_lag_30": "BDI 30 Days Ago",
  "c5_lag_1": "Route C5 Yesterday",
  "c5_lag_7": "Route C5 7 Days Ago",
  "c5_ma_7": "Route C5 7-Day Average",
  "bci_roc_7": "BCI 7-Day Rate of Change",
  "bci_roc_14": "BCI 14-Day Rate of Change",
  "c5_roc_7": "Route C5 7-Day Rate of Change",
  "iron_ore_price_usd": "Iron Ore Price ($/t)",
  "coking_coal_price_usd": "Coking Coal Price ($/t)",
  "brent_crude_usd": "Brent Crude Oil ($/bbl)",
  "bunker_fuel_vlsfo_usd": "VLSFO Bunker Fuel ($/t)",
  "china_manufacturing_pmi": "China Manufacturing PMI",
  "sp500_index": "S&P 500 Index",
  "usd_inr": "USD / INR Exchange Rate",
  "usd_cny": "USD / CNY Exchange Rate",
  "port_congestion_east_india_days": "Paradip/Vizag Port Delay (Days)",
  "port_congestion_china_days": "China Port Delay (Days)",
  "capesize_fleet_dwt_m": "Global Capesize Fleet (M DWT)",
  "vessel_orderbook_pct": "Capesize Order Book (%)",
  "cos_day_of_year": "Seasonal Cycle (Cosine)",
  "sin_day_of_year": "Seasonal Cycle (Sine)",
  "fuel_to_c5_ratio": "Fuel-to-Freight Ratio",
  "iron_ore_to_bci_ratio": "Ore-to-Shipping Ratio",
  "bci_to_bdi_ratio": "Capesize Strength Ratio",
  "is_chinese_new_year": "Chinese New Year Period",
  "is_monsoon_season": "Indian Monsoon Season",
}
